language: python
python:
- '3.5'
- '3.6'
- '3.7-dev'
cache: pip
sudo: required
script:
- python -c "import tasklogger"
- pip install -U .[test]
- if [ "$TRAVIS_PYTHON_VERSION" != "3.5" ]; then black . --check --diff; fi
- python setup.py test
deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
- coveralls
