language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
cache: pip
sudo: required
script:
- python -c "import multiscale_phate"
- pip install -U .[test]
- black . --check --diff
- nose2
deploy:
  provider: pypi
  user: mkuchroo
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
- coveralls
